-- CREE UNE VUE TYPOLOGIE_CLIENT AFFICHANT L'ID,
-- LA SOCIETE ET LE NOMBRE DE COMMANDE DE CHAQUE CLIENT
CREATE OR ALTER VIEW TYPOLOGIE_CLIENT
AS 
SELECT Cl.ClientId,Cl.NomSociete, COUNT(Co.ClientId) AS 'Nombre de commandes', 
CASE
    WHEN COUNT(Co.ClientId) <= 10 THEN 'CLIENT OCCASIONNEL'
    WHEN COUNT(Co.ClientId) BETWEEN 11 AND 20 THEN 'CLIENT FREQUENT'
    WHEN COUNT(Co.ClientId) BETWEEN 21 AND 30 THEN 'CLIENT FIDELE'
    ELSE 'SUPER CLIENT'
END AS Typologie
FROM Ventes.dbo.Client AS Cl
    LEFT JOIN Ventes.dbo.Commande AS Co ON Cl.ClientId = Co.ClientId
GROUP BY Cl.ClientId,Cl.NomSociete;