-- AJOUTE UNE CONTRAINTE PAR DEFAUT SUR LA COLONNE 'DATECREATION'
-- DANS LA TABLE ENTITE
ALTER TABLE Ventes.dbo.Entite
ADD CONSTRAINT cs default CURRENT_TIMESTAMP for [DATECREATION];

SELECT *
FROM Ventes.dbo.Entite;