-- CREE UNE TABLE LOCATAIRES
-- (LA CREATION NE SE FAIT QU'UNE SEULE FOIS)
IF NOT EXISTS(SELECT *
FROM sys.objects
WHERE object_id = OBJECT_ID(N'[dbo].[Locataires]') AND type in (N'U'))

CREATE TABLE [Ventes].[dbo].[Locataires]
(
    CODE_LOCATAIRE INT PRIMARY KEY IDENTITY(1,1),
    NOM NVARCHAR(30) not NULL,
    PRENOM NVARCHAR(30) not NULL,
    AGE INT CHECK(AGE>=18 AND AGE<=70),
    MAIL VARCHAR(100) CHECK(MAIL LIKE '%@%'),
    DATE_LOCATION DATE DEFAULT CURRENT_TIMESTAMP,
    ADRESSE VARCHAR(100),
    DEPARTEMENT INT
)

SELECT *
FROM Ventes.dbo.Locataires;