-- AJOUTE UNE CONTRAINTE DE VERIFICATION DE L'AGE
-- DANS LA TABLE LOCATAIRES
ALTER TABLE Ventes.dbo.Locataires
ADD CONSTRAINT Dpt_nb CHECK([DEPARTEMENT]>=1 AND [DEPARTEMENT]<=95);

SELECT *
FROM Ventes.dbo.Locataires;