-- AJOUTE UNE CONTRAINTE D'UNICITE DU NUM_TEL
-- DANS LA TABLE LOCATAIRES
ALTER TABLE Ventes.dbo.Locataires
ADD CONSTRAINT telephone_unique UNIQUE([NUMERO_TELEPHONE]);

SELECT *
FROM Ventes.dbo.Locataires;