-- AJOUTE UNE CONTRAINTE DE CLE PRIMAIRE SUR LE CHAMP 
--'NUM_MAISON' DANS LA TABLE MAISON
ALTER TABLE Ventes.dbo.MAISON
ADD CONSTRAINT PK_Nb_House PRIMARY KEY([NUM_MAISON]);

SELECT *
FROM Ventes.dbo.MAISON;