-- AJOUTE UNE CONTRAINTE DE CLE ETRANGERE SUR LE CHAMP 
--'CODE_LOCATAIRE' DANS LA TABLE MAISON
ALTER TABLE Ventes.dbo.MAISON
ADD CONSTRAINT FK_CODE 
    FOREIGN KEY([CODE_LOCATAIRE])
    REFERENCES Ventes.dbo.Locataires([CODE_LOCATAIRE]);

SELECT *
FROM Ventes.dbo.MAISON;