-- AJOUTE UNE CONTRAINTE CHECK SUR LE CHAMP 'SURFACE' 
-- DANS LA TABLE MAISON
ALTER TABLE Ventes.dbo.MAISON
ADD CONSTRAINT constraint_sfc CHECK([SURFACE]>=30 AND [SURFACE]<=150);

SELECT *
FROM Ventes.dbo.MAISON;